name: Release
description: Create a new release

inputs:
  role-to-assume:
    description: 'The role to assume'
    required: true
  aws-region:
    description: 'The AWS region'
    required: true
  release-artifacts-bucket:
    description: 'The S3 bucket to store release artifacts'
    required: true

runs:
  using: composite
  steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Install Dependencies
      shell: bash
      run: npm ci

    - name: Install semantic release dependencies
      shell: bash
      run: npm i semantic-release @semantic-release/changelog @semantic-release/github -D

    - name: configure aws credentials
      uses: aws-actions/configure-aws-credentials@v1.7.0
      with:
        role-to-assume: ${{ inputs.role-to-assume }}
        role-session-name: GitHub_to_AWS_via_FederatedOIDC
        aws-region: ${{ inputs.aws-region }}
          
    - name: Sts GetCallerIdentity
      shell: bash
      run: aws sts get-caller-identity

    - name: download CHANGELOG from s3
      shell: bash
      run: aws s3 cp s3://${{ inputs.release-artifacts-bucket }}/changelog/${{ github.event.repository.name }}/int/CHANGELOG.md CHANGELOG.md

    - name: Semantic Release
      shell: bash
      run: npx semantic-release

    - name: Upload CHANGELOG to Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: CHANGELOG
        path: CHANGELOG.md

    - name: Upload CHANGELOG to S3
      shell: bash
      run: aws s3 cp CHANGELOG.md s3://${{ inputs.release-artifacts-bucket }}/changelog/${{ github.event.repository.name }}/int/CHANGELOG.md

    - name: Cat changelog
      shell: bash
      run: cat CHANGELOG.md

    - name: Slack Notify
      uses: pedrobgodoy/cloud-release-slack-notify@main
      env:
        SLACK_WEBHOOK_URL: ${{ env.SLACK_WEBHOOK_URL }}
  